### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by deniak**

### CODE REVIEW

**Comment by deniak-test** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by deniak-test** [comment]
Marked as  substantive for IPR from ash-nazg.

**Comment by deniak** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by deniak** [comment]
Marked as  substantive for IPR from ash-nazg.

**Comment by deniak** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by deniak** [comment]
Marked as  substantive for IPR from ash-nazg.

**Comment by deniak** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by deniak** [comment]
Marked as  substantive for IPR from ash-nazg.

**Comment by deniak** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by deniak** [comment]
Marked as  substantive for IPR from ash-nazg.

**Pull request closed without merging**
